showTPS: true
showPing: true
TABWorldColor: true
chatWorldColor: true
#true or false

worldColor:
  world: 'DARK_GREEN'
  world_nether: 'RED'
  world_the_end: 'DARK_PURPLE'

# AQUA
# BLACK
# BLUE
# BOLD
# DARK_AQUA
# DARK_BLUE
# DARK_GRAY
# DARK_GREEN
# DARK_PURPLE
# DARK_RED
# GOLD
# GRAY
# GREEN
# ITALIC
# LIGHT_PURPLE
# MAGIC
# RED
# WHITE
# YELLOW
# UNDERLINE
