#permisions: ptab.reload
check-update: true


TABWorldColor: true
chatWorldColor: true
#true or false


enableTabText: true
header: 'you server name'
footer: 'ยง6Ping: %ping%'
#You can add -> TPS: %tps% <- (Works only on paper)
#tab text support formatting codes https://minecraft.fandom.com/wiki/Formatting_codes


worldColor:
  world: 'DARK_GREEN'
  world_nether: 'RED'
  world_the_end: 'LIGHT_PURPLE'

# AQUA
# BLACK
# BLUE
# BOLD
# DARK_AQUA
# DARK_BLUE
# DARK_GRAY
# DARK_GREEN
# DARK_PURPLE
# DARK_RED
# GOLD
# GRAY
# GREEN
# ITALIC
# LIGHT_PURPLE
# MAGIC
# RED
# WHITE
# YELLOW
# UNDERLINE
